ifdef::env-gitlab[]
include::Manual.attributes[]
include::env-gitlab.attributes[]
{link_home}

toc::[]
endif::[]

ifdef::backend-docbook5[:fig-width-default: scaledwidth=10cm]
ifdef::backend-html5,env-gitlab[:fig-width-default: width=50%]

[[chp.energybins]]
== Energy Bins
include::stylesheets/Toggle[]


[[sec.energybins.binningcmd]]
=== The BINNING Command

opal-begin
In _OPAL_, energy-bin definitions are attached to the `DISTRIBUTION`
statement.
opal-end

opalx-begin
In _OPALX_, energy binning is defined as a separate command and then
passed to the field solver as an argument.

----
BINS1: BINNING, 
    MAXBINS      = 120, 
    DESIREDWIDTH = 0.2, 
    BINNINGALPHA = 1.1, 
    BINNINGBETA  = 1.6, 
    PARAMETER    = VELOCITYZ, // Could be "VELOCITYZ", "POSITIONZ", "PZ" or "GAMMAZ"
    DUMPBINSFILE = "data/bin-dump.json",
    DUMPBINSFREQ = 1; 
----
MAXBINS::
  Maximum number of energy bins that may be created.

DESIREDWIDTH::
  Target width of each bin in the selected binning parameter.

BINNINGALPHA::
  Scale parameter used by the adaptive binning algorithm.

BINNINGBETA::
  Second scale parameter used by the adaptive binning algorithm.

PARAMETER::
  Quantity used to construct the bins. Supported values are
  `VELOCITYZ`, `POSITIONZ`, `PZ`, and `GAMMAZ`.

DUMPBINSFILE::
  Optional output file used to dump the current bin structure.

DUMPBINSFREQ::
  Frequency, in time steps, at which the bin structure is written to
  `DUMPBINSFILE`.

opalx-end
